name: Increment Version
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Increment version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ github.event.release.tag_name }} -m "[ci skip] v%s"
          git tag -f ${{ github.event.release.tag_name }}
          git push --follow-tags --force
