name: Publish Package
on:
  release:
      types: [published]
jobs:
  increment-version:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Increment version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ github.event.release.tag_name }} -m "[ci skip] v%s"
          git tag -af ${{ github.event.release.tag_name }} -m "[ci skip] v%s"
          git push
          git push origin --tags --force
  publish:
    runs-on: ubuntu-latest
    needs:
      - increment-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
