name: Publish Package
on:
  release:
      types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Update package.json version to match tag
        run: |
          npm version ${{ github.event.release.tag_name }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json
          git commit -m "NPM version bump to ${{ github.event.release.tag_name }}
          git push
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
#      - name: Publish package on NPM 📦
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
