name: Publish Package
on:
  release:
      types: [published]
jobs:
  increment-version:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Get GH Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_RELEASE_APP_ID }}
          private-key: ${{ secrets.GH_RELEASE_APP_PRIVATE_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: Increment version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git remote set-url origin https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/${{ github.repository }}
          npm version ${{ github.event.release.tag_name }} -m "[ci skip] v%s"
          git tag -af ${{ github.event.release.tag_name }} -m "[ci skip] v%s"
          git push
          git push origin --tags --force
  publish:
    runs-on: ubuntu-latest
    needs:
      - increment-version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and build 🔧
        run: npm ci
      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
